// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhHNwHP9UBVod2f36J7hNH09mJXHEciLI',
    appId: '1:340526007375:web:fa86b29eb45c4e87fed63a',
    messagingSenderId: '340526007375',
    projectId: 'diaree01-5305f',
    authDomain: 'diaree01-5305f.firebaseapp.com',
    storageBucket: 'diaree01-5305f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKp5H06L77T_QfYFLnWERNxBz7WlPXB1c',
    appId: '1:340526007375:android:1ae807b887ed183bfed63a',
    messagingSenderId: '340526007375',
    projectId: 'diaree01-5305f',
    storageBucket: 'diaree01-5305f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAtIa2jQI20b9V5hMnP8CcfpA8nt1ZE38',
    appId: '1:340526007375:ios:be5aba96d78ed87dfed63a',
    messagingSenderId: '340526007375',
    projectId: 'diaree01-5305f',
    storageBucket: 'diaree01-5305f.appspot.com',
    iosClientId: '340526007375-lq6tpsv0sjdkufi18djiu1sjrbl7481b.apps.googleusercontent.com',
    iosBundleId: 'com.example.diaree',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAtIa2jQI20b9V5hMnP8CcfpA8nt1ZE38',
    appId: '1:340526007375:ios:be5aba96d78ed87dfed63a',
    messagingSenderId: '340526007375',
    projectId: 'diaree01-5305f',
    storageBucket: 'diaree01-5305f.appspot.com',
    iosClientId: '340526007375-lq6tpsv0sjdkufi18djiu1sjrbl7481b.apps.googleusercontent.com',
    iosBundleId: 'com.example.diaree',
  );
}
